// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: jugador.proto

package go_jugador_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Peticion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peticion string `protobuf:"bytes,1,opt,name=peticion,proto3" json:"peticion,omitempty"`
}

func (x *Peticion) Reset() {
	*x = Peticion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jugador_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peticion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peticion) ProtoMessage() {}

func (x *Peticion) ProtoReflect() protoreflect.Message {
	mi := &file_jugador_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peticion.ProtoReflect.Descriptor instead.
func (*Peticion) Descriptor() ([]byte, []int) {
	return file_jugador_proto_rawDescGZIP(), []int{0}
}

func (x *Peticion) GetPeticion() string {
	if x != nil {
		return x.Peticion
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jugador_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_jugador_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_jugador_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Inicio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inicio string `protobuf:"bytes,1,opt,name=inicio,proto3" json:"inicio,omitempty"`
}

func (x *Inicio) Reset() {
	*x = Inicio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jugador_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inicio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inicio) ProtoMessage() {}

func (x *Inicio) ProtoReflect() protoreflect.Message {
	mi := &file_jugador_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inicio.ProtoReflect.Descriptor instead.
func (*Inicio) Descriptor() ([]byte, []int) {
	return file_jugador_proto_rawDescGZIP(), []int{2}
}

func (x *Inicio) GetInicio() string {
	if x != nil {
		return x.Inicio
	}
	return ""
}

type Juego struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Juego string `protobuf:"bytes,1,opt,name=juego,proto3" json:"juego,omitempty"`
}

func (x *Juego) Reset() {
	*x = Juego{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jugador_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Juego) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Juego) ProtoMessage() {}

func (x *Juego) ProtoReflect() protoreflect.Message {
	mi := &file_jugador_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Juego.ProtoReflect.Descriptor instead.
func (*Juego) Descriptor() ([]byte, []int) {
	return file_jugador_proto_rawDescGZIP(), []int{3}
}

func (x *Juego) GetJuego() string {
	if x != nil {
		return x.Juego
	}
	return ""
}

type Numero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numero  int32 `protobuf:"varint,1,opt,name=numero,proto3" json:"numero,omitempty"`
	Jugador int32 `protobuf:"varint,2,opt,name=jugador,proto3" json:"jugador,omitempty"`
}

func (x *Numero) Reset() {
	*x = Numero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jugador_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Numero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Numero) ProtoMessage() {}

func (x *Numero) ProtoReflect() protoreflect.Message {
	mi := &file_jugador_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Numero.ProtoReflect.Descriptor instead.
func (*Numero) Descriptor() ([]byte, []int) {
	return file_jugador_proto_rawDescGZIP(), []int{4}
}

func (x *Numero) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

func (x *Numero) GetJugador() int32 {
	if x != nil {
		return x.Jugador
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Ronda  int32  `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jugador_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_jugador_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_jugador_proto_rawDescGZIP(), []int{5}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Estado) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

var File_jugador_proto protoreflect.FileDescriptor

var file_jugador_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x65, 0x74, 0x69,
	0x63, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x22, 0x25, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x20, 0x0a, 0x06, 0x49, 0x6e, 0x69, 0x63, 0x69,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x22, 0x1d, 0x0a, 0x05, 0x4a, 0x75, 0x65,
	0x67, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x75, 0x65, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x75, 0x65, 0x67, 0x6f, 0x22, 0x3a, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x65,
	0x72, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x22, 0x36, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x32, 0xae, 0x01, 0x0a,
	0x09, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0f, 0x45, 0x6e,
	0x76, 0x69, 0x61, 0x72, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x12, 0x11, 0x2e,
	0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2e, 0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x1a, 0x12, 0x2e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0c, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72,
	0x49, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x12, 0x0f, 0x2e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x2e, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x1a, 0x0e, 0x2e, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x2e, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0c, 0x45, 0x6e, 0x76,
	0x69, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x0f, 0x2e, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x1a, 0x0f, 0x2e, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x00, 0x42, 0x2d, 0x5a,
	0x2b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d,
	0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f,
	0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jugador_proto_rawDescOnce sync.Once
	file_jugador_proto_rawDescData = file_jugador_proto_rawDesc
)

func file_jugador_proto_rawDescGZIP() []byte {
	file_jugador_proto_rawDescOnce.Do(func() {
		file_jugador_proto_rawDescData = protoimpl.X.CompressGZIP(file_jugador_proto_rawDescData)
	})
	return file_jugador_proto_rawDescData
}

var file_jugador_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jugador_proto_goTypes = []interface{}{
	(*Peticion)(nil),  // 0: jugador.Peticion
	(*Respuesta)(nil), // 1: jugador.Respuesta
	(*Inicio)(nil),    // 2: jugador.Inicio
	(*Juego)(nil),     // 3: jugador.Juego
	(*Numero)(nil),    // 4: jugador.Numero
	(*Estado)(nil),    // 5: jugador.Estado
}
var file_jugador_proto_depIdxs = []int32{
	0, // 0: jugador.Jugadores.EnviarSolicitud:input_type -> jugador.Peticion
	2, // 1: jugador.Jugadores.EnviarInicio:input_type -> jugador.Inicio
	4, // 2: jugador.Jugadores.EnviarJugada:input_type -> jugador.Numero
	1, // 3: jugador.Jugadores.EnviarSolicitud:output_type -> jugador.Respuesta
	3, // 4: jugador.Jugadores.EnviarInicio:output_type -> jugador.Juego
	5, // 5: jugador.Jugadores.EnviarJugada:output_type -> jugador.Estado
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jugador_proto_init() }
func file_jugador_proto_init() {
	if File_jugador_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jugador_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peticion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jugador_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jugador_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inicio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jugador_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Juego); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jugador_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Numero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jugador_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jugador_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jugador_proto_goTypes,
		DependencyIndexes: file_jugador_proto_depIdxs,
		MessageInfos:      file_jugador_proto_msgTypes,
	}.Build()
	File_jugador_proto = out.File
	file_jugador_proto_rawDesc = nil
	file_jugador_proto_goTypes = nil
	file_jugador_proto_depIdxs = nil
}
